export enum Mode {
  AUBERGINE = "AUBERGINE",
  AUBERGINE_DARK = "AUBERGINE_DARK",
  MOOD_INDIGO = "MOOD_INDIGO",
  MOOD_INDIGO_DARK = "MOOD_INDIGO_DARK",
  OCHIN = "OCHIN",
  OCHIN_DARK = "OCHIN_DARK",
}
